### ISSUE TITLE
Update the Buy/Sell mechanism

### ISSUE THREAD

**Issue by clicksave** [cartridge-gg/dopewars#185]
This is more fun. lets build a fancy slider. Can keep it simple at first and see how that goes. If we find that people really miss being able to adjust the quantity incrementally, or clicking a button to select the maximum allowed, than I have some designs for that.

Biggest thing is that this design combines the buy/sell pages. The primary button changes depending on what side of the slider you're on

Left = Sell
Right = Buy

See below

---

**Desktop**

<img src="https://uploads.linear.app/bbdecfa0-62ba-4d64-888d-44b699ecea41/b7e2a02f-a06c-4f18-a7b1-7494c1a50992/015552de-9855-4b30-bd9c-8fc2a153b478?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2JiZGVjZmEwLTYyYmEtNGQ2NC04ODhkLTQ0YjY5OWVjZWE0MS9iN2UyYTAyZi1hMDZjLTRmMTgtYTdiMS03NDk0YzFhNTA5OTIvMDE1NTUyZGUtOTg1NS00YjMwLWJkOWMtOGZjMmExNTNiNDc4IiwiaWF0IjoxNzExOTg4MDU3LCJleHAiOjMzMjgyNTQ4MDU3fQ.gemV4cdXzvK67CO6qLl7tl-IXZsP41Vov0inb9z7Hh0 " alt="image.png" width="1504" height="931" />

<img src="https://uploads.linear.app/bbdecfa0-62ba-4d64-888d-44b699ecea41/68674d15-29eb-4f47-9cc0-852321011963/ee0edd25-0c88-4484-8ba2-c753adeaa20f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2JiZGVjZmEwLTYyYmEtNGQ2NC04ODhkLTQ0YjY5OWVjZWE0MS82ODY3NGQxNS0yOWViLTRmNDctOWNjMC04NTIzMjEwMTE5NjMvZWUwZWRkMjUtMGM4OC00NDg0LThiYTItYzc1M2FkZWFhMjBmIiwiaWF0IjoxNzExOTg4MDU3LCJleHAiOjMzMjgyNTQ4MDU3fQ.8lN62pGNIBVedpW5EhMi98AudTCHKgxGIKXQdDDQFtU " alt="image.png" width="1614" height="999" />

<img src="https://uploads.linear.app/bbdecfa0-62ba-4d64-888d-44b699ecea41/2c05688a-f2cd-4457-9c1e-1b7495bf23ea/f673386b-c50c-4b3e-9c8a-bed8c4fa9fb2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2JiZGVjZmEwLTYyYmEtNGQ2NC04ODhkLTQ0YjY5OWVjZWE0MS8yYzA1Njg4YS1mMmNkLTQ0NTctOWMxZS0xYjc0OTViZjIzZWEvZjY3MzM4NmItYzUwYy00YjNlLTljOGEtYmVkOGM0ZmE5ZmIyIiwiaWF0IjoxNzExOTg4MDU3LCJleHAiOjMzMjgyNTQ4MDU3fQ.m2wsTyYcAxFzPwWsWGG1gteuLSoi5bJ0WDIjrBX5g-Y " alt="image.png" width="1614" height="1000" />

<img src="https://uploads.linear.app/bbdecfa0-62ba-4d64-888d-44b699ecea41/18a627d2-c6cc-4aa3-ac57-e4c8de94dda6/22c9d2fd-38b0-4f80-98a1-99b8cf9fd31a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2JiZGVjZmEwLTYyYmEtNGQ2NC04ODhkLTQ0YjY5OWVjZWE0MS8xOGE2MjdkMi1jNmNjLTRhYTMtYWM1Ny1lNGM4ZGU5NGRkYTYvMjJjOWQyZmQtMzhiMC00ZjgwLTk4YTEtOTliOGNmOWZkMzFhIiwiaWF0IjoxNzExOTg4MDU3LCJleHAiOjMzMjgyNTQ4MDU3fQ.u1ol-9eSlE6ygg517ZNuU6BTSNl7AEALoTaPgDeArYs " alt="image.png" width="1615" height="1001" />

**Mobile**

<img src="https://uploads.linear.app/bbdecfa0-62ba-4d64-888d-44b699ecea41/bb73884d-1530-437d-b118-3c7390a55b24/9add3843-5ed8-41d6-b69b-e42ef46af9ee?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2JiZGVjZmEwLTYyYmEtNGQ2NC04ODhkLTQ0YjY5OWVjZWE0MS9iYjczODg0ZC0xNTMwLTQzN2QtYjExOC0zYzczOTBhNTViMjQvOWFkZDM4NDMtNWVkOC00MWQ2LWI2OWItZTQyZWY0NmFmOWVlIiwiaWF0IjoxNzExOTg4MDU3LCJleHAiOjMzMjgyNTQ4MDU3fQ.V3G3L02mAzP9rOnJIF8HCwbl6JGKnoPPJPwMyoUAZv0 " alt="image.png" width="463" height="952" />

<img src="https://uploads.linear.app/bbdecfa0-62ba-4d64-888d-44b699ecea41/748f765d-0e77-4cc5-95e2-18ee033cd045/6b19cffe-0977-4d3a-8c53-1215cf0e6474?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2JiZGVjZmEwLTYyYmEtNGQ2NC04ODhkLTQ0YjY5OWVjZWE0MS83NDhmNzY1ZC0wZTc3LTRjYzUtOTVlMi0xOGVlMDMzY2QwNDUvNmIxOWNmZmUtMDk3Ny00ZDNhLThjNTMtMTIxNWNmMGU2NDc0IiwiaWF0IjoxNzExOTg4MDU3LCJleHAiOjMzMjgyNTQ4MDU3fQ.qUGb8_XbKSZBN_MbXGXGLd5uTNS-9iztGKURsoKbmvg " alt="image.png" width="1291" height="865" />

---

A few more things are happening here...

- [ ] changing the drugs back to the skeumorphic buttons (the entire card is a button again)

<img src="https://uploads.linear.app/bbdecfa0-62ba-4d64-888d-44b699ecea41/6b5ee45a-cd9e-49cb-af8e-f33b49cd7278/46b6ef8f-25ea-4995-89e4-3d1e280932ce?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2JiZGVjZmEwLTYyYmEtNGQ2NC04ODhkLTQ0YjY5OWVjZWE0MS82YjVlZTQ1YS1jZDllLTQ5Y2ItYWY4ZS1mMzNiNDljZDcyNzgvNDZiNmVmOGYtMjVlYS00OTk1LTg5ZTQtM2QxZTI4MDkzMmNlIiwiaWF0IjoxNzExOTg4MDU3LCJleHAiOjMzMjgyNTQ4MDU3fQ.9iQ3he9WbnZR9GNaE8AfMzVGTm_W3beA17TC8ijmQPw " alt="image.png" width="672" height="611" />

- [ ] Add the amount held to the buy/sell page

<img src="https://uploads.linear.app/bbdecfa0-62ba-4d64-888d-44b699ecea41/53b1b5f4-4f60-4944-b8e5-e4f7f1ee95c0/89837964-5517-468e-9bef-0faa40bda650?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2JiZGVjZmEwLTYyYmEtNGQ2NC04ODhkLTQ0YjY5OWVjZWE0MS81M2IxYjVmNC00ZjYwLTQ5NDQtYjhlNS1lNGY3ZjFlZTk1YzAvODk4Mzc5NjQtNTUxNy00NjhlLTliZWYtMGZhYTQwYmRhNjUwIiwiaWF0IjoxNzExOTg4MDU3LCJleHAiOjMzMjgyNTQ4MDU3fQ.PSxfnNAU8gC0_UQY37mv6NcpGKQKpvwJGQn45-MHzbE " alt="image.png" width="821" height="653" />

- [ ] The slider only allows you to select the 'maximum possible' here, the user only has 35 items so he can't scroll all the way to the edge

<img src="https://uploads.linear.app/bbdecfa0-62ba-4d64-888d-44b699ecea41/36761899-e164-430a-a4c2-716144300744/f133aae0-7abf-4973-9deb-173f083d6f7b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2JiZGVjZmEwLTYyYmEtNGQ2NC04ODhkLTQ0YjY5OWVjZWE0MS8zNjc2MTg5OS1lMTY0LTQzMGEtYTRjMi03MTYxNDQzMDA3NDQvZjEzM2FhZTAtN2FiZi00OTczLTlkZWItMTczZjA4M2Q2ZjdiIiwiaWF0IjoxNzExOTg4MDU3LCJleHAiOjMzMjgyNTQ4MDU3fQ.ZpD2M0z7hArJNjBFvLDE3hGeztDtUn6x8UYw9o0D4R0 " alt="image.png" width="1059" height="162" />

**Resources**

[Desktop](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=6796%3A457576&mode=design&t=MdOEY8qCXrUqYYDD-1)

[Mobile](https://www.figma.com/file/zxsaCYDghgl1Wc0Oz71lNp/RYO.app?type=design&node-id=7644%3A160761&mode=design&t=MdOEY8qCXrUqYYDD-1)

**Comment by clicksave** [comment]
Bump @notV4l 

<img width="460" alt="image" src="https://github.com/cartridge-gg/rollyourown/assets/3332646/56d99d01-cbbb-4807-97a1-c962004376f9">

Lets keep the incremental up and down arrows though

Lower priority than the other stuff

**Comment by akhercha** [comment]
Trying this one!
